name: Kwiki-RecentChanges
version: 0.13
abstract: Kwiki Plugin to Display Recent Changes
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.37
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
